
target-version = "py38"
fix = false

[lint]
extend-select = [
    "B",
    "E501",  # line too long (default 88)
    # "I",  # isort
]
# extend-safe-fixes = ["UP008"] # Do not rewrite super() calls
exclude = ["setup/*"]
ignore = [
    "UP030",
    "UP031",
    "UP032",
    "UP008",
    "B023"
    ,
    "B018","B904","E226","E241","E242","E741","F811","F601","E203"

    ]

[lint.pycodestyle]
# E501 reports lines that exceed the length of 199.
max-line-length = 199

[format]
exclude = ["setup/*"]
quote-style = "preserve"

[lint.per-file-ignores]
"__init__.py" = ["F401", "I001"]  # ignore unused and unsorted imports in __init__.py
"__manifest__.py" = ["B018"]  # useless expression

[lint.isort]
section-order = ["future", "standard-library", "third-party", "odoo", "odoo-addons", "first-party", "local-folder"]

[lint.isort.sections]
"odoo" = ["odoo"]
"odoo-addons" = ["odoo.addons"]

[lint.mccabe]
max-complexity = 16
