# Copyright 2012-2025 Akretion France (https://www.akretion.com)
# @author Alexis de Lattre <alexis.delattre@akretion.com>
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).


{
    'name': 'Account Move Import',
    'version': '18.0.2.0.0',
    'category': 'Accounting',
    'summary': 'Import account moves generated by external software',
    'license': 'AGPL-3',
    'author': 'Akretion',
    'website': 'https://github.com/akretion/account-move-import',
    'depends': ['account'],
    'demo': ['demo/demo.xml'],
    # I don't add the 'odsparsator' lib in external_dependencies
    # because it is rarely used. When trying to use ods, the user will get an explicit
    # error that tells him to install the odsparsator lib
    'external_dependencies': {'python': ['openpyxl', 'xlrd']},
    'data': [
        'security/ir.model.access.csv',
        "security/ir_rule.xml",
        'data/sequence.xml',
        'data/account_move_import_config.xml',
        'wizard/account_move_import_view.xml',
        "views/account_move_import_config.xml",
    ],
    'installable': True,
}
