# -*- encoding: utf-8 -*-
##############################################################################
#
#    Account move CSV import module for OpenERP
#    Copyright (C) 2012-2014 Akretion (http://www.akretion.com)
#    @author Alexis de Lattre <alexis.delattre@akretion.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################


{
    'name': 'Account Move CSV Import',
    'version': '1.0',
    'category': 'Accounting & Finance',
    'summary': 'Import CSV/TXT account moves generated by external software',
    'license': 'AGPL-3',
    'description': """
Account Move CSV Import
=======================

This module handle the import of one or several account moves supplied via a CSV or TXT file. This module currently supports:

* MeilleureGestion.com payroll CSV files,
* Quadra export files,
* LibreOffice CSV export files.

This module can easily be extended to support other CSV or TXT file formats.

There are many community modules that handle the import of account moves via CSV/TXT files. But I decided to develop this module because I wanted a module with the following design guidelines:

* code is easy to read
* code is easy to debug
* expressive error messages
* module with minimum dependancies

This module has been written by Alexis de Lattre from Akretion (alexis.delattre@akretion.com).
    """,
    'author': 'Akretion',
    'website': 'http://www.akretion.com',
    'depends': ['account_accountant'],
    'data': [
        'wizard/import_move_view.xml',
    ],
    'installable': True,
    'active': False,
}
