# Copyright 2024 Akretion France (http://www.akretion.com/)
# @author: Alexis de Lattre <alexis.delattre@akretion.com>
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo import _, api, fields, models
from odoo.exceptions import ValidationError

COL_FIELDS = [
    'col_date',
    'col_journal',
    'col_account',
    'col_partner',
    'col_analytic',
    'col_name',
    'col_debit',
    'col_credit',
    'col_ref',
    'col_reconcile_ref',
    'col_date_maturity',
    'col_move_name',
    ]


class AccountMoveImportConfig(models.Model):
    _name = "account.move.import.config"
    _description = "Journal Entries Import Configuration"
    _order = "sequence, id"

    sequence = fields.Integer(default=10)
    active = fields.Boolean(default=True)
    name = fields.Char(required=True, index=True)
    # The company_id field here is just for filtering, if you want to affect a config
    # to specific company, nothing more. No _check_company_auto/check_company
    company_id = fields.Many2one(
        "res.company", ondelete="cascade", index=True, required=False
    )
    file_format = fields.Selection(
        [
            ('xlsx_xls_ods', 'XLSX/XLS/ODS'),
            ('csv', 'CSV'),
            ('fec_txt', 'FEC (text)'),
            ('quadra', 'Quadra (without analytic)'),
        ],
        required=True,
        default="xlsx_xls_ods",
    )
    # Default values
    default_post_move = fields.Boolean(
        string='Post and Reconcile',
        help="If enabled, the journal entries will be posted and, if the Reconcile Ref "
        "is available in the import file, Odoo will reconcile the journal items.")
    default_force_move_ref = fields.Char('Force Reference')
    default_force_move_line_name = fields.Char('Force Label')
    # Config params
    force_move_date_required = fields.Boolean(string="Force Date is Required in Wizard")
    force_journal_id = fields.Many2one(
        'account.journal', string="Force Journal",
        company_dependent=True,
        help="Journal in which the journal entry will be created, "
        "even if the file indicate another journal.")
    sheet_number = fields.Integer(
        default=1,
        help="Sheet number to read. First sheet corresponds to sheet number 1.")
    show_sheet_number = fields.Boolean(compute="_compute_show")
    start_line = fields.Integer(default=2)
    show_start_line = fields.Boolean(compute="_compute_show")
    # Advanced options
    date_by_move_line = fields.Boolean(
        string='Is date by move line ?',
        help="If enabled, we don't use date to detect the split "
        "of journal entries.")
    skip_null_lines = fields.Boolean(
        string="Skip lines with debit = credit = 0")
    keep_odoo_move_name = fields.Boolean(
        string="Don't Force Journal Entry Name",
        help="If 'move_name' is present in the pivot format and "
        "this option is enabled, it will ignore the value of 'move_name' "
        "and use the sequence generated by Odoo when posting the journal entry.")
    split_move_method = fields.Selection([
        ('balanced', 'Balanced'),
        ('move_name', 'Journal Entry Number'),
        ], default='balanced', required=True,
        help="If you select the method 'Balanced', Odoo will create a new journal entry "
        "when a group of journal items is balanced with the same journal and date. "
        "If you select the method 'Journal Entry Number', "
        "Odoo will create a new journal entry when the field 'move_name' "
        "of the pivot format changes (this field is optional, "
        "but it will have to be present if you select this method).")
    # COLUMN config
    show_col_config = fields.Boolean(compute="_compute_show")
    col_account = fields.Selection("_sel_int2letter", string="Account Code")
    col_analytic = fields.Selection(
        "_sel_int2letter", string="Analytic Account Code",
        help="This column can contain the code of an analytic account or "
        "an analytic distribution written as 'CODE1:40|CODE2:60' "
        "for a distribution with 40% on analytic account CODE1 "
        "and 60% on analytic account CODE2.")
    col_partner = fields.Selection("_sel_int2letter", string="Partner Code")
    col_name = fields.Selection("_sel_int2letter", string="Journal Item Label")
    col_debit = fields.Selection(
        "_sel_int2letter", string="Debit",
        help="For XLSX/XLS/ODS formats, this column must be in number format.")
    col_credit = fields.Selection(
        "_sel_int2letter", string="Credit",
        help="For XLSX/XLS/ODS formats, this column must be in number format.")
    col_ref = fields.Selection("_sel_int2letter", string="Reference")
    col_journal = fields.Selection("_sel_int2letter", string="Journal Code")
    col_date = fields.Selection(
        "_sel_int2letter", string="Date",
        help="For XLSX/XLS/ODS formats, this column must be in date format "
        "(or be in text format and written in the syntax configured in the "
        "'Date Format' parameter).")
    col_date_maturity = fields.Selection(
        "_sel_int2letter", string="Due Date",
        help="For XLSX/XLS/ODS formats, this column must be in date format "
        "(or be in text format and written in the syntax configured in the "
        "'Date Format' parameter).")
    col_move_name = fields.Selection("_sel_int2letter", string="Journal Entry Number")
    col_reconcile_ref = fields.Selection(
        "_sel_int2letter", string="Reconcile Ref",
        help="Used for reconciliation of the imported journal items "
        "if the option 'Post and Reconcile' is enabled.")

    # CSV fields parameters (encoding is also used by FEC)
    show_csv_config = fields.Boolean(compute="_compute_show")
    encoding = fields.Selection(
        [
            ("iso8859_15", "ISO-8859-15"),
            ("utf-8", "UTF-8"),
            ("ascii", "ASCII"),
        ],
        default="iso8859_15",
        required=True,
    )
    show_encoding = fields.Boolean(compute="_compute_show")
    delimiter = fields.Selection(
        [
            (",", "coma"),
            (";", "semi-colon"),
            ("|", "pipe"),
            ("tab", "tab"),
        ],
        default=",",
        required=True,
        string="Field Delimiter",
    )
    date_format = fields.Char(
        default="%d/%m/%Y",
        required=True,
        help="For XLSX/XLS/ODS format, this configuration is used only "
        "when the date column is in text format instead of date format ; "
        "otherwise it is ignored.\n"
        "Syntax:\n%d for day,\n%m for month,\n"
        "%Y for year on 4 digits,\n%y for year on 2 digits.")
    show_date_format = fields.Boolean(compute="_compute_show")
    decimal_separator = fields.Selection(
        [
            (".", "dot"),
            (",", "coma"),
        ],
        default=".",
        required=True,
    )
    quoting = fields.Selection(
        [
            ("minimal", "Minimal"),
            ("all", "All"),
            ("none", "None"),
        ],
        default="minimal",
        required=True,
    )

    _sql_constraints = [
        (
            "name_company_uniq",
            "unique(name, company_id)",
            "An import configuration already exists with the same name.",
        ),
        (
            "start_line_positive",
            "CHECK(start_line > 0)",
            "The start line must be strictly positive.",
        ),
        (
            "sheet_number_positive",
            "CHECK(sheet_number > 0)",
            "The sheet number must be strictly positive.",
        ),
    ]

    def _get_file_format_info(self):
        res = {
            'xlsx_xls_ods': {
                'cols': True,
                "start_line": True,
                'sheet_number': True,
                "date_format": True,
                },
            'csv': {
                'cols': True,
                'csv': True,  # it includes encoding
                "start_line": True,
                "date_format": True,
                },
            'fec_txt': {
                'encoding': True,
                },
            'quadra': {},
            }
        return res

    @api.depends('file_format')
    def _compute_show(self):
        fileformat2info = self._get_file_format_info()
        for config in self:
            show_col_config = show_csv_config = show_start_line = False
            show_encoding = show_sheet_number = show_date_format = False
            if config.file_format:
                config_dict = fileformat2info[config.file_format]
                show_col_config = config_dict.get('cols')
                show_csv_config = config_dict.get('csv')
                show_start_line = config_dict.get('start_line')
                show_encoding = config_dict.get('encoding')
                show_sheet_number = config_dict.get('sheet_number')
                show_date_format = config_dict.get("date_format")
            config.show_col_config = show_col_config
            config.show_csv_config = show_csv_config
            config.show_start_line = show_start_line
            config.show_encoding = show_encoding
            config.show_sheet_number = show_sheet_number
            config.show_date_format = show_date_format

    @api.model
    def _sel_int2letter(self):
        res = []  # [('0', 'A'), ('1', 'B'), ('2', 'C'), ...]
        for position in range(25):
            res.append((str(position), chr(position + 65)))
        return res

    @api.constrains(
            "file_format",
            'col_account', 'col_analytic', 'col_partner', 'col_name',
            'col_credit', 'col_debit', 'col_ref', 'col_journal', 'col_date',
            'col_move_name', 'col_reconcile_ref')
    def _check_cols(self):
        required_col_fields = [
            "col_account",
            "col_credit",
            "col_debit",
            ]
        field2label = dict([(key, vals['string']) for key, vals in self.fields_get(attributes=['string']).items()])
        for config in self:
            colpos2name = {}
            for col_field in COL_FIELDS:
                if config[col_field]:
                    if config[col_field] in colpos2name:
                        raise ValidationError(_(
                            "On configuration '%(config)s', the column '%(col1)s' is "
                            "configured with the same position as column '%(col2)s'.",
                            config=config.display_name,
                            col1=field2label[col_field],
                            col2=field2label[colpos2name[config[col_field]]],
                            ))
                    colpos2name[config[col_field]] = col_field
            if config.file_format in ("xlsx_xls_ods", "csv"):
                for col_field in required_col_fields:
                    if not config[col_field]:
                        raise ValidationError(_(
                            "On configuration '%(config)s', the column '%(col)s' "
                            "is not configured (this column is required).",
                            config=config.display_name,
                            col=field2label[col_field],
                            ))

    def _get_pfield2position(self):
        self.ensure_one()
        pfield2position = {}
        for col_field in COL_FIELDS:
            position_str = self[col_field]
            # WARNING : position_str can be '0'
            if position_str:
                position = int(position_str)
            else:
                position = None
            pfield2position[col_field[4:]] = position
        return pfield2position
